spring:
  h2:
    console:
      path: /h2-console
      enabled: true
  datasource:
    url: jdbc:h2:mem:homework
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true # ???? ???? ``? ????.
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
        open-in-view: false

decorator:
  datasource:
    p6spy:
      enable-logging: off